services:
  db:
    image: postgres:17-alpine
    container_name: hospital-db
    environment:
      POSTGRES_DB: hospital_management
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - hospital-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d hospital_management"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: jdk25-psql:latest
    container_name: hospital-app
    ports:
      - "8080:8080"
    volumes:
      - ./target:/app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://hospital-db:5432/hospital_management
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - hospital-net
    depends_on:
      db:
        condition: service_healthy
    # Ensure the app starts using the correct shell form to handle the JAR
    command: ["java", "-jar", "/app/HospitalManagement-0.0.1-SNAPSHOT.jar"]

networks:
  hospital-net:

volumes:
  db_data: